dataset: loft
data_dir: hotpotqa_32k
model: /home/rethinkingai-self/25m0820/kvpress/Qwen3-8B-AWQ
device: cuda:0
press_name: kvzip
compression_ratio: 0.01
key_channel_compression_ratio: null
memory_budget: 2.0
memory_budget_unit: GB
fraction: 1.0
max_new_tokens: 100
max_context_length: null
query_aware: false
needle_depth: null
compression_interval: null
target_size: null
hidden_states_buffer_size: null
output_dir: ./results_loft32k_qwen_awq_yarn4_fullcontext_all_budgets
log_level: INFO
model_kwargs:
  attn_implementation: null
  dtype: auto
  max_position_embeddings: 131072
  rope_parameters:
    rope_type: yarn
    factor: 4.0
    original_max_position_embeddings: 32768
    rope_theta: 1000000
press_init_command: KVzipPress(compression_ratio=0.01, layerwise=False, n_sink=4,
  kvzip_plus_normalization=False)
seed: 42
fp8: false
int8: false
int4: false
